name: CI

on:
  workflow_dispatch:

jobs:
  setup-and-quality:
    name: Setup & Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for class usage
        run: |
          chmod +x ./scripts/check-no-classes.sh
          ./scripts/check-no-classes.sh

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint src test --ext .ts,.tsx

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Build check
        run: npm run build --if-present
